[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/slack/atlan-setup"
  to = "/.netlify/functions/slack-command"
  status = 200

[[redirects]]
  from = "/test" 
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/health"
  status = 200
